### PR TITLE
DEVOPS-209/handle-merge-failure

### PR DESCRIPTION
**Pull request by cwsatpolymath**
* Handle merge conflict failures by fetching with a different strategy before notifying error.

### CODE REVIEW

**Comment by cwsatpolymath** [comment]
Needs more work

**Review by maxsam4 — APPROVED** [review]

**Comment by adamdossa** [comment]
@cwsatpolymath based on your comment, should this PR be marked as draft or WIP?

**Comment by cwsatpolymath** [comment]
> @cwsatpolymath based on your comment, should this PR be marked as draft or WIP?

@adamdossa The comment was before I closed and reopened the PR.  This is ready from my end.

**Review by adamdossa — APPROVED** [review]

**Comment by cwsatpolymath** [comment]
Closing PR since DEVOPS-211 includes the changes here.

**Pull request closed without merging**
