### PR TITLE
MESH-1658/audit bridge pallet

### PR DESCRIPTION
**Pull request by Neopallium**
Code cleanup and audit.

### modified API

- Added event `BridgeTxScheduleFailed` for when scheduling a transaction failed.

### modified logic

- Extrinsic `change_bridge_limit` will throw error `DivisionByZero` if `duration == 0`.
- Errors `NoValidCdd`, `DivisionByZero`, `Overflow`, `BridgeLimitReached` are now reported correctly.

### modified agent functionality

- Event `BridgeTxScheduleFailed` can be emitted by extrinsics `force_handle_bridge_tx`, `batch_propose_bridge_tx`, `propose_bridge_tx`, `handle_bridge_tx`, `unfreeze_txs`, `handle_scheduled_bridge_tx`.

### CODE REVIEW

**Comment by Neopallium** [comment]
There are a few errors in `fn issue` that are silently ignored:

1. `NoValidCdd`
2. `DivisionByZero` - Previously the bridge admin could set the duration of the bridge limit to 0 and all transaction would have silently failed.  All transaction would have been stuck in the `Pending` status.
3. `Overlow` - Not likely to ever happen, unless the admin is forcing multiple transactions with massive POLYX.
4. `BridgeLimitReached`
 
1 & 4 are more likely to happen, but the error will not be seen on the network, the transactions will just stay in the `Pending` status until the bridge limit duration passes or the receiver gets their CDD claim.

I would recommend adding an event for these errors, since the transaction still needs to be (re)scheduled to run again.

**Comment by Neopallium** [comment]
This PR is WIP until we decide what to do with the ignored errors in `fn issue`.

**Comment by Centril** [comment]
> I would recommend adding an event for these errors, since the transaction still needs to be (re)scheduled to run again.

Seems like a good plan.

**Comment by adamdossa** [comment]
> There are a few errors in `fn issue` that are silently ignored:
> 
> 1. `NoValidCdd`
> 2. `DivisionByZero` - Previously the bridge admin could set the duration of the bridge limit to 0 and all transaction would have silently failed.  All transaction would have been stuck in the `Pending` status.  I have added a restriction on setting the bridge limit `duration` to 0.
> 3. `Overlow` - Not likely to ever happen, unless the admin is forcing multiple transactions with massive POLYX.
> 4. `BridgeLimitReached`
> 
> 1 & 4 are more likely to happen, but the error will not be seen on the network, the transactions will just stay in the `Pending` status until the bridge limit duration passes or the receiver gets their CDD claim.
> 
> I would recommend adding an event for these errors, since the transaction still needs to be (re)scheduled to run again.

Agree adding events for these makes sense.

**Review by Centril — APPROVED** [review]

**Review by Centril — APPROVED** [review]

**Review by adamdossa — APPROVED** [review]

**Pull request merged**
