### PR TITLE
[WIP] MESH-1640/issue with add secondary keys with auth

### PR DESCRIPTION
**Pull request by Neopallium**
Add test case and fix the 1-to-1 constraint check.

### new features

None.

### modified API

None.

### modified logic

- Fix 1-to-1 account to DID constraint check in `add_secondary_keys_with_authoration`

### CODE REVIEW

**Comment by Neopallium** [comment]
> I think this logic won't work in the case that `si.signer` is of type `Signatory::Identity`. In that case, `account_id` will be the primary key of the identity that is joining:
> `Signatory::Identity(id) => Self::identity_record_of(id).map(|r| r.primary_key)`
> which will therefore be linked to `id` already (and fail `can_link_account_key_to_did`).
>
> The doc:
> https://developers.polymesh.live/polymesh-docs/primitives/identity
> gives an overview of the idea that an Identity (as well as an "external" key) can be secondary key of an identity. Having said that, we might depreciate this functionality in favour of External Agents (cc @Centril ).

Ah.  So my current "fix" is not correct, since it would always reject this use-case.  I missed the check later that skips the `link_account_key_to_did` if the signer was an identity.

Right now the same secondary key (identity) can be added multiple times because of the `PartialEq` bug that was found earlier.  I was looking at removing the `sort` and `dedup` calls when adding a secondary key and was checking to see if there was any way a duplicate secondary key could be added, which lead me to this issue.

If we want to keep this use-case, then we will need to keep the sort & dedup or check if the identity is already a secondary key.

> work when `bob_account_signer` hasn't been previously joined to the identity (i.e. I don't see why we'd get the `AlreadyLinked` error).

That is using Bob's primary key which is linked to his Identity.  His primary key can't be used as a secondary key, but his identity can.

> For the FIXME lines in the test cases, it's because we're not checking for `Signatory::Identity`'s that the DID isn't already linked to the identity (i.e. that it is a no-op) - we should check for this case though and throw an error `DidAlreadyLinkedToIdentity` or just return Ok() (probably better to throw an error).

If we keep the use-case of adding an Identity as a secondary key, then we should check if that identity is already in the secondary keys list and throw the `AlreadyLinked` error.  Right now it just keeps adding the identity as a secondary key and then tries to remove duplicates (the sort/dedup).  But if you add the same identity multiple times with different permissions, then the dedup will not remove the duplicate identities.

**Comment by Neopallium** [comment]
So this issue just exposes the `PartialEq` bug in MESH-1628.  It also shows why we needed to do the sort & dedup when adding a secondary key.

Options:

1. Keep the sort/dedup of the secondary_keys list.  This would still emit a `SecondaryKeysAdded` event, even if the identity already was in the secondary keys list.
2. Check if the identity is already in the secondary_keys list and throw `AlreadyLinked` error.  We could then remove the sort/dedup lowering the cost, since a `find` is cheaper then a `sort`/`dedup`.

I think option 2 is best.

**Comment by adamdossa** [comment]
@Neopallium Option 2. sounds best for now. Will this still prevent the same key (either an `AccountId` or an `IdentityId`) being added twice to the same identity with different permissions?

For keys which are `Signatory::Identity` they can be linked to multiple identities - it is only keys of type `Signatory::Account` which can only be linked to a single identity.

**Comment by F-OBrien** [comment]
> So this issue just exposes the `PartialEq` bug in MESH-1628. It also shows why we needed to do the sort & dedup when adding a secondary key.
> 
> Options:
> 
> 1. Keep the sort/dedup of the secondary_keys list.  This would still emit a `SecondaryKeysAdded` event, even if the identity already was in the secondary keys list.
> 2. Check if the identity is already in the secondary_keys list and throw `AlreadyLinked` error.  We could then remove the sort/dedup lowering the cost, since a `find` is cheaper then a `sort`/`dedup`.
> 
> I think option 2 is best.

I agree that option 2 is probably the best and was what I was thinking when I highlighted this to @adamdossa. There is a 3rd option (and probably more). You could do similar to `update_secondary_key_permission` and use `retain` on everything else so if it already exists it is deleted and then `push` the key again. This eliminates the possibility of duplication ensuring the latest key is the one with the newest permissions without need for sort and dedup, since dedup doesn't seem to work for differing permissions anyway.
I still prefer option 2 as I feel if the identity or key already existed it should fail with an error, so the person who was trying to add the key is prompted to check existing keys and associated permissions rather than unknowingly overriding any permissions that may have existed.

**Comment by Neopallium** [comment]
> @Neopallium Option 2. sounds best for now. Will this still prevent the same key (either an `AccountId` or an `IdentityId`) being added twice to the same identity with different permissions?

Yes.
Also `fn base_join_identity` will need to check the secondary_keys list before adding the new secondary key.  So there are two functions that need to do this check.

**Comment by Neopallium** [comment]
I have corrected the new test, since the issue is with adding an `Signatory::Identity` secondary key.  Using different permissions will cause duplicates to be added.

**Comment by Neopallium** [comment]
Using PR #1018 instead of this one, since the bug is really with the `PartialEq`.  Still using Option 2 for fixing the issue with duplicate secondary keys.

**Pull request closed without merging**
