### PR TITLE
Fix deserialization from `jsonrpc` for the RPC interface.

### PR DESCRIPTION
**Pull request by Neopallium**
Polkadot's RPC serializes rust enum variant type names to lowercase.  This seems to only affect rust style enums like our `Singatory` enum.

This PR uses `#[serde(alias = "identity")]` variant attribute to allow deserialize from the lowercase variant name.

### CODE REVIEW

**Comment by adamdossa** [comment]
Would it be better to use something like:
`#[serde(rename_all = "snake_case")]` rather than doing each type separately?

**Comment by Neopallium** [comment]
> Would it be better to use something like:
> `#[serde(rename_all = "lowercase")]` rather than doing each type separately?

I was worried that something else was using the "correct case".  Using alias still allows the previous case style.

We can try it and see if anything breaks.

**Review by adamdossa — APPROVED** [review]

**Comment by Neopallium** [comment]
> Would it be better to use something like:
> `#[serde(rename_all = "lowercase")]` rather than doing each type separately?

Looks like we will need to do that for enums returned from RPC methods.

**Comment by Neopallium** [comment]
I think we can fix the `u128` issue here too.  Doing some testing using relayer.

**Comment by Neopallium** [comment]
Removed the 'rpc-check' from circleci since it was only checking for `u128` types in the RPC interface.

**Review by satyamakgec — APPROVED** [review]

**Pull request merged**
