### PR TITLE
Fix bug in primary key (PK) rotation

### PR DESCRIPTION
**Pull request by Centril**
### modified logic

- Fix bug in primary key (PK) rotation where key already being attached to DID was allowed.

### CODE REVIEW

**Comment by satyamakgec** [comment]
@Centril are you planning to write the migrations as well?

**Comment by F-OBrien** [comment]
Just a comment on this fix for consideration. While it prevents the possibility of assigning a key as primary that is already assigned to to someone else it also prevents you from assigning one of your own secondary keys directly as as a primary. This may be the intended behaviour. If a user wanted to assign a secondary key as primary they need to first remove it as a secondary key.

Alternatively, if a user does not have a secondary account and they rotate the primary key to a new key, they need to transfer POLYX from external source before they would be able to rejoin the old primary key as a secondary to allow them to transfer any POLYX funds out of that account. I think it may be preferable if the old primary became a secondary automatically. Or a more controversial option would be for the transferring of primary key to "kill" the old primary account and transfer all POLYX automatically.

**Comment by Centril** [comment]
Initially this is the fix we went with but decided to simplify towards the current implementation, accepting the drawbacks you mention.

**Comment by adamdossa** [comment]
> Alternatively, if a user does not have a secondary account and they rotate the primary key to a new key, they need to transfer POLYX from external source before they would be able to rejoin the old primary key as a secondary to allow them to transfer any POLYX funds out of that account. I think it may be preferable if the old primary became a secondary automatically. Or a more controversial option would be for the transferring of primary key to "kill" the old primary account and transfer all POLYX automatically.

@F-OBrien you could transfer POLYX out of the original Primary Key after issuing the authorisation request to the new Primary Key (or before, provided you leave enough to call `add_authorisation(RotatePrimaryKey)`). The new Primary Key can then invite the original Primary Key to rejoin the identity as a Secondary Key if desired.

When accepting a Primary Key rotation, or joining an identity as a Secondary Key, the key issuing the authorization pays for the transaction (from the target key) to accept the authorisation.

**Comment by F-OBrien** [comment]
> @F-OBrien you could transfer POLYX out of the original Primary Key after issuing the authorisation request to the new Primary Key (or before, provided you leave enough to call `add_authorisation(RotatePrimaryKey)`). The new Primary Key can then invite the original Primary Key to rejoin the identity as a Secondary Key if desired.
> 
> When accepting a Primary Key rotation, or joining an identity as a Secondary Key, the key issuing the authorization pays for the transaction (from the target key) to accept the authorisation.

Thanks, yes I'm aware there are ways to do it, just extra steps. I guess it shouldn't be too common a requirement anyway. Another option is to create a secondary key, with permissions to call rotatePK and transfer all funds from the primary to it. Then use the secondary key to call rotatePK to the new key. That way I believe the secondary key gets charged the fee, when the new primary accepts, and you can just forget about the old primary.

**Pull request merged**
