### PR TITLE
MESH-993/ Cleanup permissioned validators

### PR DESCRIPTION
**Pull request by satyamakgec**

### CODE REVIEW

**Comment by satyamakgec** [comment]
we are going to push this in Aldebaran then we can test `onRuntimeUpgrade` xD

**Comment by satyamakgec** [comment]
Yeah we need migration for this but still not decided how we are gonna play so keeping as it once we decided to merge this Aldebaran, I will add the migration within `onRuntimeUpgrade`.

**Comment by adamdossa** [comment]
@satyam approved for merging. I will split out a separate story for permissioning via identity. This would be for V2 though only.

**Comment by Satyam** [comment]
@adamdossa You cited me @satyam instead of @satyamakgec whom, I assume, you actually meant.

**Comment by satyamakgec** [comment]
Yeah sorry @Satyam, Adam meant @satyamakgec.

**Pull request merged**
