### PR TITLE
Mesh 991/granular errors

### PR DESCRIPTION
**Pull request by maxsam4**

### CODE REVIEW

**Comment by maxsam4** [comment]
Sample output
```json
{
  "jsonrpc": "2.0",
  "result": {
    "final_result": true,
    "is_paused": false,
    "rules": [
      {
        "receiver_rules": [],
        "rule_id": 1,
        "sender_rules": [
          {
            "result": false,
            "rule": {
              "issuers": [
                "0x0600000000000000000000000000000000000000000000000000000000000000"
              ],
              "rule_type": {
                "IsPresent": {
                  "Accredited": "0x0100000000000000000000000000000000000000000000000000000000000000"
                }
              }
            }
          }
        ],
        "transfer_rule_result": false
      },
      {
        "receiver_rules": [
          {
            "result": false,
            "rule": {
              "issuers": [
                "0x0600000000000000000000000000000000000000000000000000000000000000"
              ],
              "rule_type": {
                "IsPresent": {
                  "Whitelisted": "0x0100000000000000000000000000000000000000000000000000000000000000"
                }
              }
            }
          },
          {
            "result": true,
            "rule": {
              "issuers": [
                "0x0600000000000000000000000000000000000000000000000000000000000000"
              ],
              "rule_type": {
                "IsAbsent": {
                  "BuyLockup": "0x0100000000000000000000000000000000000000000000000000000000000000"
                }
              }
            }
          }
        ],
        "rule_id": 2,
        "sender_rules": [
          {
            "result": true,
            "rule": {
              "issuers": [
                "0x0600000000000000000000000000000000000000000000000000000000000000"
              ],
              "rule_type": {
                "IsAbsent": {
                  "SellLockup": "0x0100000000000000000000000000000000000000000000000000000000000000"
                }
              }
            }
          },
          {
            "result": false,
            "rule": {
              "issuers": [
                "0x0600000000000000000000000000000000000000000000000000000000000000"
              ],
              "rule_type": {
                "IsAnyOf": [
                  {
                    "Whitelisted": "0x0100000000000000000000000000000000000000000000000000000000000000"
                  },
                  {
                    "Affiliate": "0x0100000000000000000000000000000000000000000000000000000000000000"
                  }
                ]
              }
            }
          }
        ],
        "transfer_rule_result": true
      }
    ]
  },
  "id": 1
}
```

**Comment by adamdossa** [comment]
@maxsam4 LGTM. Is anything else needed to put this through as a network upgrade?

**Comment by maxsam4** [comment]
Tested on a local branch, no changes are needed to put this through as a network upgrade.

**Comment by maxsam4** [comment]
The data returned and functions called by both RPCs are very different. I think it makes sense to keep it separate for now.

The asset_canTransfer will require a major refactor to be standardized to support custom errors like this. I think we should add a new story for it.

**Pull request merged**
