### PR TITLE
Add error types to schema.

### PR DESCRIPTION
**Pull request by Neopallium**
Improve error decoding by adding enums for module errors to the schema.

### new features

- Add generated error types to `errors_schema.json` for improved error decoding.

### CODE REVIEW

**Review by raycar5 — APPROVED** [review]
Nice!

**Review by raycar5 — CHANGES_REQUESTED** [review]
Actually, it seems it creates problems with the integration tests so it could create problems with the sdk error handling code, I think it's a good change but probably should be left out of this release so we have time to investigate its ramifications properly

**Comment by Neopallium** [comment]
> Actually, it seems it creates problems with the integration tests so it could create problems with the sdk error handling code, I think it's a good change but probably should be left out of this release so we have time to investigate its ramifications properly

This PR is more of a RFC (request for comment).  I will take a look at the integration tests.

But we could use the new types to improve Subscan and our polkadot.js web apps.  The schema for those are updated manually.

**Comment by Neopallium** [comment]
These error types might be better as an extra schema that we can manually add for the webapps that can use it.

**Comment by Neopallium** [comment]
I moved the generated error types to a different schema file `errors_schema.json`.

These types are not needed for the Polymesh SDK, because Polkadot.js provides a way to dynamically lookup module errors.  But that is not used in the Polkadot.js webapp.  So we can use these types in `https://testnet-app.polymesh.live/` and `https://mainnet-app.polymesh.live/` for easier to understand errors.

**Review by raycar5 — APPROVED** [review]

**Review by Centril — APPROVED** [review]

**Pull request merged**
