### PR TITLE
[WIP]: fix: RPC canTransfer() result schema

### PR DESCRIPTION
**Pull request by satyamakgec**

### CODE REVIEW

**Review by Centril — APPROVED** [review]

**Comment by adamdossa** [comment]
Can we leave this open for a bit please. I am going to go through and clean up the branches over the weekend, so will merge then.

**Comment by satyamakgec** [comment]
@adamdossa tagged with WIP tag, Once you have done with cleanup you can merge this by removing the WIP tag

**Comment by adamdossa** [comment]
@satyamakgec This can be closed. I cherry-picked the `develop` branch version into `tooling_v2.2.0` which will be later merged into `tooling`.

**Comment by satyamakgec** [comment]
Closing as required change is appended in the `tooling_v2.0.0`

**Pull request closed without merging**
