### PR TITLE
[WIP] Move out runtime from pallets

### PR DESCRIPTION
**Pull request by fmiguelgarcia**
New folder structure:
- any pallet is inside `core/pallets` folder.
- runtimes & polymesh-runtime-common are into `core/runtime` folder.
- primitives & its derive crate are in `core`.
- `polymesh-common-utilities` has been moved from `pallets` to `core`.

### CODE REVIEW

**Review by satyamakgec — APPROVED** [review]
I think it is nice to have segregation. But possibly it may break some of the links within the external documentations.

**Review by Centril — APPROVED** [review]

**Comment by fmiguelgarcia** [comment]
@satyamakgec I've just generated the doc and links look good. They are using their `crate paths`, like `polymesh_primitives::identity_id::IdentityId`, which have not been changed.
Did you refer those kind of links?

**Comment by satyamakgec** [comment]
No @fmiguelgarcia, I am more concerned about the other documentations that lives over polymesh.developer... URL but I think we can merge as the content of those docs already stale so may gonna update those docs anyway.

**Review by vkomenda — APPROVED** [review]

**Review by maxsam4 — COMMENTED** [review]
LGTM but I'd suggest doing the overhaul post v1/audit.

**Comment by adamdossa** [comment]
@fmiguelgarcia can we hold off merging until I've had a chance to separate out the V1 release in terms of branches - aiming to do that shortly.

**Comment by maxsam4** [comment]
End of an era xD

**Comment by Centril** [comment]
Those were the good old days ;)

**Pull request closed without merging**
