### PR TITLE
MESH-1916 Monthly 2022 12

### PR DESCRIPTION
**Pull request by Neopallium**
### new features

- Update to Substrate monthly 2022-12.
- Move to V2 Weights (now includes a `proof_size`).

### modified API

- The Contract pallet RPC endpoints have been removed and can only be accessed as Runtime Calls (`state_call` RPC endpoint).
- Added `payment_queryFeeDetails` RPC endpoint.
- Added Runtime APIs `TransactionPaymentCallApi_query_call_info` and `TransactionPaymentCallApi_query_call_fee_details`.  Used to query the cost of a call without having to first sign a transaction with that call.
- Added event `transaction-payment.TransactionFeePaid` to record tx fees.

### modified logic

- The `Weight` type has been changed from just a single `u64` to a pair (ref_time and proof_size).

### data migration

- Substrate pallet migrations in `pallet_contracts`, `pallet_scheduler`, `pallet_preimage`.

### CODE REVIEW

**Comment by Neopallium** [comment]
TODO:

- [x] Publish new versions of `confidential-identity-*` crates.
- [x] Check that no new migrations are needed between Substrate monthly 11 and 12.
- [x] Test Substrate migrations by upgrading a development chain.  (do two runtime upgrades, to make sure migrations don't run multiple times).
- [x] Need to check that a node with the newer Substrate monthly release can still do a full sync of Testnet and Mainnet.  This is to check if [ed25519_verify change](https://github.com/paritytech/substrate/pull/12661) hasn't caused a problem.
- [x] Re-run benchmarks to update pallets missed last time.

**Review by HenriqueNogara — APPROVED** [review]
LGTM. I was expecting even more changes

**Comment by Neopallium** [comment]
Most of the changes were the `Runtime` prefix and V2 Weights, which covers a lot of files/code.  The biggest function change was moving to a different JSON-RPC crate created by paritytech.

**Review by adamdossa — APPROVED** [review]

**Comment by Neopallium** [comment]
FYI, marking as WIP to block merging until the NFT PR is merged and we are ready for this.

**Pull request merged**
