### PR TITLE
Tooling v2.2.0

### PR DESCRIPTION
**Pull request by adamdossa**
Adds Governance V2
Removes unnecessary runtime upgrade functions for Alcyone 2.1 to 2.2 upgrade
Enables compiled WASM
Fixes `reject_instruction` in Settlement code
Updated bootnode identity

### CODE REVIEW

**Review by satyamakgec — APPROVED** [review]
Just want to confirm, majorly we introduced the latest PIP and committee features.

**Comment by Centril** [comment]
@adamdossa please take a look at https://github.com/PolymathNetwork/Polymesh/pull/725#pullrequestreview-526037618 re. the migration code removal.

**Comment by adamdossa** [comment]
> Just want to confirm, majorly we introduced the latest PIP and committee features.

Yep - this release functionally just contains Governance V2.

**Review by maxsam4 — APPROVED** [review]
pme is at 2006 spec version so we'd need to bump it more or do an unchecked upgrade.

**Comment by adamdossa** [comment]
> pme is at 2006 spec version so we'd need to bump it more or do an unchecked upgrade.

@maxsam4 probably easiest to do an unchecked upgrade - alcyone is at 2004, so that would realign PME & Alcyone.

**Pull request merged**
