### PR TITLE
Mesh 1124/refactor settlements using transaction rollbacks

### PR DESCRIPTION
**Pull request by maxsam4**
- Instead of manually undoing failed actions, the settlement module now uses substrate's new transaction rollback feature.
- Updated name of test crate

Tagged everyone as a reviewer because this is a new and exciting substrate feature that everyone might be interested in.

Ps The actual relevant changes are in the [settlement module](https://github.com/PolymathNetwork/polymesh-settlement-module/compare/49e0dfd96993e220e375c72296b7b9a6881d0d7d...141455da88252c28494ed92b05a350b262d6a63e).

### CODE REVIEW

**Comment by satyamakgec** [comment]
Yeah, it is an exciting feature and by seeing an implementation it seems easy to apply as well. 

If I am not wrong transaction rollback work in 3 phases -

`with_transaction()` allow you to put the changes which you want to rollback if some condition doesn't meet until unless you explicitly call the `commit()` (commit the changes in the storage from the overlay).

`rollback()` rollback the changes whatever performed in `with_transaction()` block as those changes are lives in the overlay layer

**Comment by Centril** [comment]
Also, another thing to consider is the `_ => ...` branch in `fn unchecked_release_locks`. One thing you'll often see in rust-lang/rust is to avoid `_ => ...` arms and instead exhaustively list all the variants. This is done to force us to consider the logic should new variants be added. It makes sense to do that in sensitive code-bases where executing the wrong code may have severe consequences, and Polymesh seems like such a codebase to me.

**Comment by maxsam4** [comment]
@satyamakgec Yeah, that's basically how it works.

Another interesting feature is that you can also nest these overlays. i.e. you can call `with_transaction` within `with_transaction` as well.

**Comment by adamdossa** [comment]
Looks very neat! @maxsam4 is it possible / easy / hard to right UTs around the functionality?

**Comment by maxsam4** [comment]
@adamdossa re. UT, There's no special requirement. The current UTs remain unchanged and they already check that the storage is not modified when it is not supposed to be.

**Pull request merged**
