### PR TITLE
Fix asset RPC

### PR DESCRIPTION
**Pull request by satyamakgec**

### CODE REVIEW

**Comment by satyamakgec** [comment]
@monitz87 could you please review this, It is kind of hack only as `number::NumberOrHex` is not supportable for `u128` type, It only works for the u64 only but out Balance type is u128.

**Comment by monitz87** [comment]
Also, shouldn't this change be applied to all custom RPC inputs that have a numerical value with 64 bits or more? (I think `buffer_time` in `identity_isIdentityHasValidCdd` is the only other one)

**Review by maxsam4 — COMMENTED** [review]
We can merge it as it is but keep in mind that anything greater than u64::MAX will not work.

**Review by adamdossa — APPROVED** [review]

**Comment by adamdossa** [comment]
@satyamakgec @monitz87 Is this ready to be merged?

**Review by maxsam4 — APPROVED** [review]

**Pull request merged**
