### PR TITLE
Removed submodules

### PR DESCRIPTION
**Pull request by maxsam4**

### CODE REVIEW

**Comment by cwsatpolymath** [comment]
This looks good, but the Concourse pipeline build script will need to have an intermediate stage to handle backwards compatible builds, something like

```
if [<condition>]; then
  submodule init steps
fi
```

Can you please provide such a condition?

**Review by Centril — APPROVED** [review]
Yay! 🎉

**Comment by maxsam4** [comment]
> This looks good, but the Concourse pipeline build script will need to have an intermediate stage to handle backwards compatible builds, something like
> 
> ```
> if [<condition>]; then
>   submodule init steps
> fi
> ```
> 
> Can you please provide such a condition?
```
if [ -e .gitmodules ]; then
   submodule init steps
fi
```
You'd have to do the dir traversal but the logic is that a file named `.gitmodules` exists in branches that require the submodule stuff but not in the branches that don't require it.

**Comment by cwsatpolymath** [comment]
https://github.com/PolymathNetwork/concourse/pull/4 should be approved and merged before this is merged.

**Review by satyamakgec — APPROVED** [review]

**Pull request merged**
